import type { Metadata } from "next";
import "./globals.css";
import { inter } from "./ui/fonts";
import Header from "./ui/header"
import Footer from "./ui/footer"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className}`}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

