import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

// components/Header.tsx
function Header() {
  return (
    <header className="bg-black text-white border-b border-gray-800 relative">
      {/* Subtle neon glow */}
      <div className="absolute inset-0 bg-gradient-to-r from-cyan-900/10 to-purple-900/10"></div>
      
      <div className="relative max-w-6xl mx-auto px-6 py-4">
        <div className="flex justify-between items-center">
          {/* Logo */}
          <div className="flex items-center">
            <h1 className="text-xl font-bold text-cyan-400 drop-shadow-[0_0_10px_rgba(34,211,238,0.5)]">
              NEON<span className="text-purple-400">TECH</span>
            </h1>
          </div>
          
          {/* Navigation */}
          <nav className="hidden md:flex space-x-8">
            {['Home', 'About', 'Services', 'Contact'].map((item) => (
              <a 
                key={item}
                href="#" 
                className="text-gray-300 hover:text-cyan-400 text-sm font-medium transition-colors duration-300 hover:drop-shadow-[0_0_5px_rgba(34,211,238,0.5)]"
              >
                {item}
              </a>
            ))}
          </nav>
          
          {/* CTA Button */}
          <div className="flex items-center space-x-4">
            <button className="hidden md:block px-4 py-2 bg-gradient-to-r from-cyan-500 to-purple-500 text-white rounded text-sm font-medium hover:shadow-[0_0_15px_rgba(34,211,238,0.5)] transition-all duration-300">
              Get Started
            </button>
            
            {/* Mobile Menu Button */}
            <button className="md:hidden w-8 h-8 border border-cyan-400 rounded flex items-center justify-center hover:bg-cyan-400/20 transition-all">
              <span className="text-cyan-400 text-xs">≡</span>
            </button>
          </div>
        </div>
      </div>
    </header>
  )
}

// components/Footer.tsx
function Footer() {
  return (
    <footer className="bg-black text-white relative">
      {/* Neon glow background */}
      <div className="absolute inset-0 bg-gradient-to-r from-cyan-900/10 to-purple-900/10"></div>
      
      <div className="relative max-w-6xl mx-auto px-6 py-12">
        {/* Main Content */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-8">
          {/* Brand */}
          <div>
            <h3 className="text-2xl font-bold text-cyan-400 drop-shadow-[0_0_10px_rgba(34,211,238,0.5)] mb-4">
              NEON<span className="text-purple-400">TECH</span>
            </h3>
            <p className="text-gray-300 text-sm mb-4">
              Cutting-edge digital solutions for the future.
            </p>
            {/* Social Links */}
            <div className="flex space-x-3">
              {['X', 'in', '@'].map((icon, i) => (
                <a key={i} href="#" className="w-8 h-8 border border-cyan-400 rounded flex items-center justify-center hover:bg-cyan-400/20 hover:shadow-[0_0_10px_rgba(34,211,238,0.5)] transition-all text-cyan-400 text-xs">
                  {icon}
                </a>
              ))}
            </div>
          </div>
          
          {/* Links */}
          <div>
            <h4 className="text-cyan-400 font-semibold mb-4 uppercase tracking-wide">Links</h4>
            <div className="space-y-2">
              {['Home', 'About', 'Services', 'Contact'].map((link) => (
                <a key={link} href="#" className="block text-gray-300 hover:text-cyan-400 text-sm transition-colors hover:pl-2">
                  {link}
                </a>
              ))}
            </div>
          </div>
          
          {/* Newsletter */}
          <div>
            <h4 className="text-purple-400 font-semibold mb-4 uppercase tracking-wide">Stay Updated</h4>
            <div className="flex mb-4">
              <input 
                type="email" 
                placeholder="Enter email"
                className="flex-1 px-3 py-2 bg-gray-900 border border-gray-700 rounded-l text-white placeholder-gray-500 focus:outline-none focus:border-cyan-400 text-sm"
              />
              <button className="px-4 py-2 bg-gradient-to-r from-cyan-500 to-purple-500 rounded-r text-sm hover:shadow-[0_0_10px_rgba(34,211,238,0.5)] transition-all">
                →
              </button>
            </div>
            <p className="text-gray-400 text-xs">
              <span className="text-cyan-400">●</span> hello@neontech.com
            </p>
          </div>
        </div>
        
        {/* Bottom */}
        <div className="border-t border-gray-800 pt-6 flex flex-col md:flex-row justify-between items-center">
          <p className="text-gray-400 text-sm mb-4 md:mb-0">
            © 2024 NeonTech. <span className="text-cyan-400">All rights reserved.</span>
          </p>
          <div className="flex space-x-4">
            {['Privacy', 'Terms', 'Cookies'].map((item) => (
              <a key={item} href="#" className="text-gray-400 hover:text-cyan-400 text-sm transition-colors">
                {item}
              </a>
            ))}
          </div>
        </div>
      </div>
    </footer>
  )
}
